### PR TITLE
ci: Add pre-commit

### LINKED ISSUE #11: Add pre-commit.ci
@rikab, would you enable [pre-commit](https://pre-commit.ci/)? 

Once that is done, I can submit a PR with the appropriate hooks!

### PR DESCRIPTION
**Pull request by j-s-ashley**
Adds pre-commit to resolve #11.

### CODE REVIEW

**Comment by j-s-ashley** [comment]
@matthewfeickert, mind giving this a review?

**Review by matthewfeickert — COMMENTED** [review]
@j-s-ashley Looks good, but I would rebase and squash the pre-commit.ci changes that were pushed back with your previous commit so that all the changes are in 1 commit.

**Comment by matthewfeickert** [comment]
I should also say that in a follow up PR to this PR, to keep `git blame` treating everything here as a real change (this is all cosmetic) a `.git-blame-ignore-revs` file can be used to have GitHub automatically ignore the commit that will be generated when this is merged.

c.f. https://github.com/matplotlib/matplotlib/pull/22809 for an example of this.

**Review by henryiii — APPROVED** [review]
Removing unused whitespace is good change, IMO. :)

**Review by matthewfeickert — APPROVED** [review]
> That's why I'd personally leave these in two commits, and rebase and merge.

That's what I was trying to communicate, but I see how my 

> all the changes are in 1 commit.

could be confusing (I meant all the pre-commit applied changes).

Anyway, this LGTM so @rikab this is ready for your review.

**Comment by matthewfeickert** [comment]
@rikab Ping on merging this.

**Pull request merged**
